import type { Metadata } from "next";
import { inter } from "@/app/fonts";
import "./globals.css";
import { Navbar } from "@/widgets/Navbar";
import { StoreProviders } from "@/app/store/storeProvider";
import { PersistedStoreProviders } from "@/app/store/persistedStoreProvider";
import { QueryProvider } from "@/app/queryProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<StoreProviders>
			<QueryProvider>
				<html lang="en">
					<body className={`${inter.className}`}>
						<Navbar />
						<PersistedStoreProviders>{children}</PersistedStoreProviders>
					</body>
				</html>
			</QueryProvider>
		</StoreProviders>
	);
}
